name: ?? CI/CD - ASP.NET Core + Docker VPS Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ?? Repo'yu klonla
      uses: actions/checkout@v3

    - name: ?? .NET kurulumu
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: ?? Nuget restore
      run: dotnet restore

    - name: ??? Build
      run: dotnet build --no-restore --configuration Release

    - name: ?? Yayýn dosyasý oluþtur (opsiyonel)
      run: dotnet publish --no-build --configuration Release -o publish

    - name: ?? VPS'e baðlan ve deploy et
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 2510
        script: |
          cd /project/beratoksz
          git reset --hard HEAD
          git pull origin main
          docker compose down
          docker compose build
          docker compose up -d
          docker system prune -f
